github:
  - safaa-shawkiy        # حساب شخصي
  - telentrasahshmedia   # حساب الشركة

custom:
  - https://ko-fi.com/behindthelightssash
  - https://ko-fi.com/telentrasahshmedia
  - https://www.paypal.com/paypalme/sh2020
  - https://www.paypal.com/paypalme/infosah
